Amazon.UI/Components/MenuViewComponent.cs
using Amazon.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Amazon.UI.Components
{
    public class MenuViewComponent:ViewComponent
    {
        private ICategoryService categoryservice;

        public MenuViewComponent(ICategoryService categoryService)
        {
            this.categoryservice = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            var categories = categoryservice.GetCategories();
            return View(categories);
        }
    }
}

Amazon.UI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.Business.Abstract;
using Amazon.UI.Extensions;
using Amazon.UI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Amazon.UI.Controllers
{
    public class CartController : Controller
    {
        private IProductService productService;

        public CartController(IProductService productService)
        {
            this.productService = productService;
        }
        public IActionResult Index()
        {
            Cart cart = GetCart();
            return View(cart);
        }

        public IActionResult AddToCart(int productId)
        {
            var product = productService.GetById(productId);
            if (product==null)
            {
                return BadRequest();
            }
            Cart cart = GetCart();
            cart.AddItem(product, 1);
            SaveCart(cart);

            return Json("OK");
        }
        public IActionResult RemoveCart(int id)
        {
            Cart cart = GetCart();
            var product = productService.GetById(id);
            cart.Remove(product);
            SaveCart(cart);
            return Json("OK");
        }

        public Cart GetCart()
        {
         
            Cart cart = HttpContext.Session.GetJson<Cart>("sepetim") ?? new Cart();
            return cart;
        } 

      
        void SaveCart(Cart cart)
        {
            HttpContext.Session.SetString("isOnline", "true");
            HttpContext.Session.SetJson("sepetim", cart);
        }
    }
}

Amazon.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Amazon.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/alertify/css/alertify.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Amazon.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Cart" asp-action="Index">Sepetim</a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark " asp-area="" asp-controller="Account" asp-action="LogOut">Merhaba @User.Identity.Name (Çıkış Yap)</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark " asp-area="" asp-controller="Account" asp-action="Login">Giriş Yap</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-3">
                    @await Component.InvokeAsync("Menu")
                </div>
                <div class="col-9">
                    @RenderBody()
                </div>
               
            </div>
          
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Amazon.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/alertify/alertify.min.js"></script>
  
  
    @RenderSection("Scripts", required: false)
</body>
</html>

Amazon.UI/Views/Shared/_ProductCard.cshtml
@model Amazon.Entities.Concrete.Product

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<div class="col-3">
    <div class="card ">
        <div class="card-body">
            <img class="card-img-top" height="150" src="@Model.ImageUrl" alt="Card image">
            <p class="card-title"><strong>@Model.ProductName </strong> </p>
            <p class="card-text">@Model.Description</p>
            <p class="text-danger">@Model.Price ₺</p>
            <button class="btn btn-success sepet" data-id="@Model.ProductId" data-name="@Model.ProductName"> Sepete Ekle   </button>
        </div>
    </div>
</div> 